# Generated by Django 5.0.6 on 2024-05-21 06:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lapp", "0002_order_stock"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="placed_by",
            new_name="buyer",
        ),
    ]
