# Generated by Django 5.0.6 on 2024-05-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lapp", "0004_remove_order_buyer"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="placed_by",
            field=models.CharField(default="Buyer", max_length=300),
        ),
    ]
