# Generated by Django 5.0.6 on 2024-05-21 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lapp", "0005_order_placed_by"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Stock",
            new_name="SupplierStock",
        ),
    ]
