# Generated by Django 5.0.6 on 2024-05-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lapp", "0006_rename_stock_supplierstock"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuyerStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier", models.CharField(max_length=300)),
                ("item", models.CharField(max_length=300)),
                ("quantity", models.IntegerField()),
                ("stock_added_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrderHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier", models.CharField(max_length=300)),
                ("item", models.CharField(max_length=300)),
                ("quantity", models.IntegerField()),
                ("completion_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(default="Pending", max_length=300),
        ),
    ]
