# Generated by Django 5.0.6 on 2024-05-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lapp", "0007_buyerstock_orderhistory_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderhistory",
            name="status",
            field=models.CharField(default="Pending", max_length=300),
        ),
    ]
