# Generated by Django 5.0.6 on 2024-05-22 05:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lapp", "0008_orderhistory_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderhistory",
            old_name="completion_date",
            new_name="date",
        ),
    ]
