# Generated by Django 5.0.6 on 2024-05-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lapp", "0009_rename_completion_date_orderhistory_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderhistory",
            name="buyer",
            field=models.CharField(default="Buyer", max_length=300),
        ),
    ]
