# Generated by Django 5.0.6 on 2024-05-22 06:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lapp", "0011_supplieritem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SupplierItem",
        ),
    ]
