# Generated by Django 5.0.6 on 2024-05-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lapp", "0012_delete_supplieritem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="unit_price",
            field=models.IntegerField(default=0),
        ),
    ]
