# Generated by Django 5.0.6 on 2024-05-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lapp", "0013_order_total_price_order_unit_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderhistory",
            name="total_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(default="Pending Payment", max_length=300),
        ),
    ]
